# Nvim compatibility
set -sg escape-time 0
set -g focus-events on

# Terminal colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Prefix
unbind "C-b"
set -g prefix "C-Space"
bind "C-Space" send-prefix

# Logs
set -g history-limit 100000

# Mouse
set -g mouse on

# Vim-style pane selection
setw -g mode-keys "vi"
bind 'h' select-pane -L
bind 'j' select-pane -D
bind 'k' select-pane -U
bind 'l' select-pane -R

# Terminator-style splits
unbind '"'
unbind '%'
unbind 'o'
bind 'e' split-window -h -c "#{pane_current_path}"
bind 'o' split-window -v -c "#{pane_current_path}"

# Quick reload
bind 'r' source-file "~/.tmux.conf" \; display "Reloaded"

# Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-resurrect"

# Initialize TPM (must be the last line)
run "~/.tmux/plugins/tpm/tpm"
